# Generated by Django 5.1 on 2024-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reyting',
            name='value',
            field=models.CharField(choices=[('5', 'Star 5'), ('4', 'Star 4'), ('3', 'Star 3'), ('2', 'Star 2'), ('1', 'Star 1'), ('0', 'Star 0')], default='0', max_length=2),
        ),
    ]
